### ISSUE TITLE
Converge failing probably because of empty mirror list.

### ISSUE THREAD

**Issue by cvakiitho** [chef-cookbooks/yum-repoforge#13]
### Cookbook version
version '0.7.0'

### Chef-client version
Chef Development Kit Version: 0.7.0
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.2

### Platform Details
Win 7 64 bit

### Scenario:
kitchen converge

### Steps to Reproduce:
git clone
kitchen converge

### Expected Result:
converge ok

### Actual Result:
Converge failed 

     Error executing action `create` on resource 'yum_repository[rpmforge]'
                ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[yum clean metadata rpmforge] (/tmp/kitchen/cache/cookbooks/yum/providers/repository.rb line 63) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of yum clean metadata --disablerepo=* --enablerepo=rpmforge ----
           STDOUT: Loaded plugins: fastestmirror
           Loading mirror speeds from cached hostfile
           STDERR: Cannot find a valid baseurl for repo: rpmforge
           ---- End output of yum clean metadata --disablerepo=* --enablerepo=rpmforge ----
           Ran yum clean metadata --disablerepo=* --enablerepo=rpmforge returned 1

Hi, all my cookbooks dependent on yum-repoforge are now failing, I actually believe it is because mirrorlist is returning empty files, but want to check here first

mirrorlist "http://mirrorlist.repoforge.org/el5/mirrors-rpmforge"

**Comment by pbattilega** [comment]
The resource this cookbook uses is considered dead according to the CentOS wiki.
https://wiki.centos.org/AdditionalResources/Repositories
“RPMForge/RepoForge - This is a dead project. Not maintained. DO NOT USE. ”

I noticed this whilst working on a cookbook that includes this one as a dependency .

**Comment by cvakiitho** [comment]
As a quick/temporary fix, we can update mirrorlist links to raw.github  #14

**Comment by cvakiitho** [comment]
upstream issue in repoforge mirrorlist is fixed now.
