### ISSUE TITLE
Chef 13 compatibilty breaks the cookbook attribute change

### ISSUE THREAD

**Issue by jmauro** [chef-cookbooks/yum-repoforge#8]
Hey,

Since the last 28th October, the cookbook doesn't handle attributes changes correctly.
```
 gpgkey node['yum'][repo]['gpgkey'] if node['yum'][repo]['gpgkey']
```
In my case I would want to set `default['yum']['repoforge'] = false`, so the `if` test will not pass, and my setting is not set.

Regards,
JM

**Comment by jmauro** [comment]
Hey, 

Me again, it seems to be a weird issue since the 0.5.5 is not reflected into master, is that on purpose?

**Comment by someara** [comment]
Hey. Looks like 0.5.5 was a release version number mistake... I've updated
the cookbook for Chef 13 and released as 0.5.6.

**Comment by jmauro** [comment]
I don't see any tag v0.5.6.

**Comment by someara** [comment]
https://github.com/chef-cookbooks/yum-repoforge/tree/v0.5.6
https://supermarket.chef.io/cookbooks/yum-repoforge/versions/0.5.6

**Comment by jmauro** [comment]
Thanks for the quick fix

**Comment by jmauro** [comment]
Still a typo in the code, I just created the PR fixing it: https://github.com/chef-cookbooks/yum-repoforge/pull/9
